name: sweptie
description: "Instantly transform your chaotic screenshot folder into a fully searchable database."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # OCR
  google_ml_kit: ^0.21.0

  # Gallery access + manual image picking
  photo_manager: ^3.3.0
  image_picker: ^1.2.1

  # Local database
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4

  # Utilities
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
